### ISSUE TITLE
cannot run ssh: no such file or directory

### ISSUE THREAD

**Issue by glerma** [coveo/tgf#70]
Problem:  When running terragrunt using modules with source pointing to git repos, errors occur when attempting to access the source with ssh authentication.

[terragrunt:Terraform/S3] 2019/05/19 00:14:54.713 [31mERROR    - module.s3
  Updating source "git@github.com:rootleveltech/rlt-aws-s3.git//source?ref=v1.3"
[31mError loading modules: error downloading 'ssh://git@github.com/rootleveltech/rlt-aws-s3.git?ref=v1.3': /usr/bin/git exited with 128: Cloning into '.terraform/modules/e741b2731ee3faf37c0604f0abd29872'...
error: cannot run ssh: No such file or directory

Not sure what is going on, but perhaps missing openssl-client?

**Comment by jocgir** [comment]
Which version of the tgf image are you using?

I added openssh-client to the latest images. Please, tell me if that solves your problem.

**Comment by glerma** [comment]
I was using latest, but if you have a new version w/ openssh-client, i'll try again and give you feedback shortly.  Thanks!

**Comment by glerma** [comment]
It seems to work fine now, using latest.  Resolved. Thank you!

**Comment by Tiny-wlx** [comment]
which version did you used? i use 1.21.0, it seems not work for me in my OSX

aaa (master) tgf plan                                                                                                                                            
[terragrunt:main] 2019/06/23 11:27:10.999 ERROR    error downloading 'ssh://git@xxx:xxx/dop/infrastructure-modules?ref=0.1.67': /usr/bin/git exited with 128: Cloning into '/tmp/tf759519972/module'...
error: cannot run ssh: No such file or directory
fatal: unable to fork

➜ aaa (master) tgf --current-version                                                                                                                               
tgf v1.21.0

**Comment by jocgir** [comment]
Hi @Tiny-wlx, could you retry?

I think the problem came because someone published a previous version of the tgf-image and that version has been marked as the latest. I just pushed a new release of the v2 image (that include the openssh client).

**Comment by Tiny-wlx** [comment]
Hi @jocgir , Thank you for your reply.

It worked as expected after pull new images.

Thank you very much.

**Comment by ifeanyiA** [comment]
Run pkg install openssh
